pipeline {
    agent any 
    stages {
        stage("uptime") {
            steps {
                sh '''
                uptime
                '''
            }
        }
        stage("Ram-Used") {
            steps {
                sh '''
                free -h
                '''
            }
        }
        stage("disk-file") {
            steps {
                sh '''
                df -kh
                '''
            }
        }
         stage("disk-usage") {
            steps {
                sh '''
                du -sch
                '''
            }
        }
        stage("poll-scm-chenking") {
            steps {
                sh '''
                echo "chenking wheather poll scm works or not"
                '''
            }
        }
    }
}